POST http://127.0.0.1:8000/api/login HTTP/1.1 
Content-Type: application/json

{
    "email": "guluisgustavo300@gmail.com", 
    "password": "12345678"
}

##################
POST http://127.0.0.1:8000/api/editarPerfil HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1",
    "name": "Luís", 
    "email": "guluisgustavo300@gmail.com", 
    "password": "12345678",
    "turma": "3",
    "curso": "Informática",
    "matricula": "2024020102",
    "descricaoEsportiva": "jogo futebol",
    "genero": "masculino",
    "dataNascimento": "2007-01-26"
}


////////////////////////////////////////////////////////////////////////////
##################
POST http://127.0.0.1:8000/api/cadastrarReserva HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1",
    "dia": "2024-12-12",
    "horarioInicio": "13:00",
    "horarioFim": "14:00",
    "finalidade": "jogar futebol",
    "status": "P",
    "tipo": "normal",
    "numeroPessoas": "30",
    "local": "Ginásio"
}


##############################
GET http://127.0.0.1:8000/api/listarReservas HTTP/1.1 
Content-Type: application/json

{

}


##################
POST http://127.0.0.1:8000/api/realizarChekin HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1",
    "idTreino": "1"
}


##############################
GET http://127.0.0.1:8000/api/listarTreinos HTTP/1.1 
Content-Type: application/json

{

}

##################
POST http://127.0.0.1:8000/api/cancelarChekin HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1",
    "idTreino": "1"
}


##################
POST http://127.0.0.1:8000/api/mostrarChekins HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1"
}


##################
POST http://127.0.0.1:8000/api/mostrarReservas HTTP/1.1 
Content-Type: application/json

{
    "idAluno": "1"
}


##############################
GET http://127.0.0.1:8000/api/listarNoticias HTTP/1.1 
Content-Type: application/json

{

}