POST http://127.0.0.1:8000/api/login HTTP/1.1 
Content-Type: application/json

{
    "email": "luis@gmail.com", 
    "password": "123"
}

##################
POST http://127.0.0.1:8000/api/listarAlunos HTTP/1.1 
Content-Type: application/json

{
    "idTime": "1"
}
